apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: srujan6868/api-gateway
    newTag: dev-placeholder
  - name: srujan6868/users-service
    newTag: dev-placeholder
